updating BoostETH contract
torquefi/torque_contracts pull request #150
Opened 2024-01-22 18:16 UTC by acemihir

2024-01-22 20:08 UTC, 99pswork commented on contracts/TorqueProtocol/strategies/GMXV2ETH.sol
> +        gmToken.safeTransfer(msg.sender, gmAmount);
Why convert this to single function ? 
The deposit function and calling createDepositParams() looks more clean

2024-01-22 20:23 UTC, 99pswork requested changes

2024-01-22 20:23 UTC, 99pswork commented on contracts/TorqueProtocol/strategies/GMXV2ETH.sol
> +        weth.safeTransfer(msg.sender, wethAmount);
Similarly here
Why convert this to a single function? 
The withdraw function and calling createDepositParams() look clean.

2024-01-22 20:23 UTC, 99pswork commented on contracts/TorqueProtocol/strategies/GMXV2ETH.sol
>      }
Why convert this to a single function?
The deposit function and calling createDepositParams() looks clean

2024-01-22 20:23 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> -import "@chainlink/contracts/src/v0.8/automation/AutomationCompatible.sol";
Please add the Torque ascii again

2024-01-22 20:23 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> +
This doesn't looks right, please explain

2024-01-22 20:23 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> +        uint256 stargateDepositAmount = depositAmount.mul(stargateAllocation).div(100);
We are taking WETH as deposits 
No need to make the function payable

2024-01-22 20:23 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(msg.sender).transfer(withdrawAmount);
Will be paying out in WETH

2024-01-22 20:23 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> -
Please add the chainlink automation logic and import

2024-01-22 21:33 UTC, acemihir commented on contracts/TorqueProtocol/strategies/GMXV2ETH.sol
> +        weth.safeTransfer(msg.sender, wethAmount);
I just added because we don't need to separate them

2024-01-22 21:33 UTC, acemihir commented on contracts/TorqueProtocol/strategies/GMXV2ETH.sol
>      }
The same reason as withdrawal function

2024-01-22 21:34 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> -import "@chainlink/contracts/src/v0.8/automation/AutomationCompatible.sol";
ok, I will

2024-01-22 21:36 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> +
I know. Its WETH contract in Ethereum. I set it for test.
I will update it with correct Arbitrum WETH address

2024-01-22 21:44 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> +        uint256 stargateDepositAmount = depositAmount.mul(stargateAllocation).div(100);
agreed

2024-01-22 21:44 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(msg.sender).transfer(withdrawAmount);
agreed

2024-01-22 21:44 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> -
I will

2024-01-23 14:17 UTC, 99pswork commented on contracts/TorqueProtocol/strategies/GMXV2ETH.sol
> +        weth.safeTransfer(msg.sender, wethAmount);
Could you please write in that format ? it looks clean and should be trying to avoid large functions as far as possible

2024-01-24 07:54 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(msg.sender).transfer(withdrawAmount);
Please fix this
transferring WETH from contract to user you can directly use IERC20(asset).transfer(msg.sender, WETHWithdraw)

2024-01-24 07:54 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> +        return (supply==0) ? shares : shares.mulDiv(totalAssets(), supply, Math.Rounding.Down);
Please explain overriding these internal functions ?

2024-01-24 07:54 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(treasury).transfer(treasuryFee);
payable is only needed for native currency transfer ?

2024-01-24 07:54 UTC, 99pswork commented on contracts/TorqueProtocol/interfaces/IWETH9.sol
> -    returns (bool);
please revert these, we need these functions 
you need to fix payable syntax.

2024-01-24 07:56 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> +    address payable private constant  WETH = payable(0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2);
you dont need to make the WETH address payable

2024-01-24 19:07 UTC, 99pswork requested changes

2024-01-24 21:17 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(msg.sender).transfer(withdrawAmount);
ok, I will update so that sending WETH, not ETH

2024-01-24 21:24 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(treasury).transfer(treasuryFee);
yes, it should be "address payable"

2024-01-24 21:27 UTC, acemihir commented on contracts/TorqueProtocol/interfaces/IWETH9.sol
> -    returns (bool);
I updated IWETH9 with IWETH9 is IERC20
Removed functions are implemented in IERC20 :)

2024-01-24 21:40 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> +    address payable private constant  WETH = payable(0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2);
i already removed it

2024-01-24 22:00 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(msg.sender).transfer(withdrawAmount);
ok, I will update

2024-01-24 22:00 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(treasury).transfer(treasuryFee);
yes, it need to be "address payable"

2024-01-24 22:01 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> +    address payable private constant  WETH = payable(0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2);
I removed it

2024-01-24 22:02 UTC, acemihir commented on contracts/TorqueProtocol/interfaces/IWETH9.sol
> -    returns (bool);
Removed functions are all implemented in IERC20
so I changed IWETH9 to "IWETH9 is IERC20"
its simple

2024-01-25 07:27 UTC, 99pswork commented on contracts/TorqueProtocol/interfaces/IWETH9.sol
> -    returns (bool);
ok, sounds good

2024-01-25 07:28 UTC, 99pswork requested changes

2024-01-25 07:28 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(treasury).transfer(treasuryFee);
We are trying to pay WETH right? why not use transfer ?

2024-01-25 10:19 UTC, acemihir commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(treasury).transfer(treasuryFee);
Sure, We can just transfer WETH to treasury. I just wanted to send eth to treasury
We only should update a little for weth transfer - just like this
weth.transfer(treasury, treasuryFee)

2024-01-25 10:29 UTC, 99pswork commented on contracts/TorqueProtocol/BoostETH.sol
> +        payable(treasury).transfer(treasuryFee);
yes exactly, please quickly fix this using a commit so that we can merge.

2024-01-25 14:28 UTC, merged